### ISSUE TITLE
Having trouble when upgrading to latest version

### ISSUE THREAD

**Issue by iam-Zedgar** [ryansch/docker-unifi-rpi#56]
I tried upgrading to latest version using:
```
docker-compose stop
docker-compose rm -f
docker-compose pull   
docker-compose up -d
```

and this happened:
https://hastebin.com/vonahuxoxa.terminal

**Comment by ryansch** [comment]
I've never seen that failure mode before. Try `docker-compose down` and then `docker-compose up -d`.

Worst case scenario you can remove all of your volumes with (BIG FAT WARNING) `docker-compose down -v` and set the controller up from a unifi backup.

**Comment by iam-Zedgar** [comment]
Tried everything. I even created whole new docker container for it and nothing. Still same error:
```pi@raspberrypi:~/unifi-new $ docker-compose logs -f
Attaching to unifi-new
unifi-new | Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils
unifi-new | 	at com.ubnt.ace.class.super(Unknown Source)
unifi-new | 	at com.ubnt.service.ooOO.Q.<clinit>(Unknown Source)
unifi-new | 	at com.ubnt.ace.Launcher.<clinit>(Unknown Source)
unifi-new | Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang.StringUtils
unifi-new | 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
unifi-new | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
unifi-new | 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
unifi-new | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
unifi-new | 	... 3 more
unifi-new | Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils
unifi-new | 	at com.ubnt.ace.class.super(Unknown Source)
unifi-new | 	at com.ubnt.service.ooOO.Q.<clinit>(Unknown Source)
unifi-new | 	at com.ubnt.ace.Launcher.<clinit>(Unknown Source)
unifi-new | Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang.StringUtils
unifi-new | 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
unifi-new | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
unifi-new | 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
unifi-new | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
unifi-new | 	... 3 more```

**Comment by iam-Zedgar** [comment]
Can it be system Java related?

**Comment by iam-Zedgar** [comment]
Resolved! WOAH! 😀

Did this:
```
cd ~
rm -rf unifi
docker image prune
docker volume prune
docker container prune
```
and still nothing..

then i removed all containers, images, volumes using:
```
docker volume rm unifidocker rmi $(docker volume ls |grep 'unifi')
docker volume rm unifidocker rmi $(docker volume ls |grep 'unifi')
```

**Comment by iam-Zedgar** [comment]
did
```
docker rmi $(docker volume ls |grep 'unifi') && 
docker rmi $(docker image ls |grep 'unifi') && 
docker rmi $(docker container ls |grep 'unifi')
```
and installed it again and now it works.

**Comment by ryansch** [comment]
That's _really_ strange. Thanks for sharing your resolution in case anyone else runs into this!

Also let me know if it happens again on the next upgrade @iam-Zedgar.
