### ISSUE TITLE
MongoDB fails with memory issues (bulk write related)

### ISSUE THREAD

**Issue by juriansluiman** [ryansch/docker-unifi-rpi#90]
This keeps going on in my logs every 30 seconds, I think this relates to the internal MongoDB version:

```cmd
[2021-12-21T20:55:29,679] <inform_stat-1> ERROR dev    - Error in DeviceManager.processStat()
com.mongodb.BulkWriteException: Bulk write operation error on server localhost:27117. Write errors: [BulkWriteError{index=10, code=10084, message='can't map file memory - mongo requires 64 bit build for larger datasets', details={ "n" : 0 , "connectionId" : 9}}, BulkWriteError{index=13, code=10084, message='can't map file memory - mongo requires 64 bit build for larger datasets', details={ "n" : 0 , "connectionId" : 9}}, BulkWriteError{index=14, code=10084, message='can't map file memory - mongo requires 64 bit build for larger datasets', details={ "n" : 0 , "connectionId" : 9}}, BulkWriteError{index=15, code=10084, message='can't map file memory - mongo requires 64 bit build for larger datasets', details={ "n" : 0 , "connectionId" : 9}}, BulkWriteError{index=16, code=10084, message='can't map file memory - mongo requires 64 bit build for larger datasets', details={ "n" : 0 , "connectionId" : 9}}, BulkWriteError{index=17, code=10084, message='can't map file memory - mongo requires 64 bit build for larger datasets', details={ "n" : 0 , "connectionId" : 9}}, BulkWriteError{index=19, code=10084, message='can't map file memory - mongo requires 64 bit build for larger datasets', details={ "n" : 0 , "connectionId" : 9}}]. 
        at com.mongodb.BulkWriteHelper.translateBulkWriteException(BulkWriteHelper.java:56) ~[mongo-java-driver-3.4.3.jar:?]
        at com.mongodb.DBCollection.executeBulkWriteOperation(DBCollection.java:2313) ~[mongo-java-driver-3.4.3.jar:?]
        at com.mongodb.DBCollection.executeBulkWriteOperation(DBCollection.java:2302) ~[mongo-java-driver-3.4.3.jar:?]
        at com.mongodb.BulkWriteOperation.execute(BulkWriteOperation.java:121) ~[mongo-java-driver-3.4.3.jar:?]
        at com.ubnt.service.system.null.o00000(Unknown Source) ~[ace.jar:?]
        at com.ubnt.service.devmgr.Ooo0.o00000(Unknown Source) ~[ace.jar:?]
        at com.ubnt.service.devmgr.Ooo0.ö00000(Unknown Source) ~[ace.jar:?]
        at com.ubnt.service.devmgr.Ooo0.o00000(Unknown Source) ~[ace.jar:?]
        at com.ubnt.service.devmgr.Ooo0.o00000(Unknown Source) ~[ace.jar:?]
        at com.ubnt.service.devmgr.KA.o00000(Unknown Source) ~[ace.jar:?]
        at com.ubnt.service.devmgr.oOo0$_o.run(Unknown Source) [ace.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[2021-12-21T20:55:56,365] <inform_stat-1> ERROR dev    - Error in DeviceManager.processStat()
com.mongodb.BulkWriteException: Bulk write operation error on server localhost:27117. Write errors: [BulkWriteError{index=13, code=10084, message='can't map file memory - mongo requires 64 bit build for larger datasets', details={ "n" : 0 , "connectionId" : 9}}, BulkWriteError{index=15, code=10084, message='can't map file memory - mongo requires 64 bit build for larger datasets', details={ "n" : 0 , "connectionId" : 9}}, BulkWriteError{index=16, code=10084, message='can't map file memory - mongo requires 64 bit build for larger datasets', details={ "n" : 0 , "connectionId" : 9}}, BulkWriteError{index=17, code=10084, message='can't map file memory - mongo requires 64 bit build for larger datasets', details={ "n" : 0 , "connectionId" : 9}}]. 
        at com.mongodb.BulkWriteHelper.translateBulkWriteException(BulkWriteHelper.java:56) ~[mongo-java-driver-3.4.3.jar:?]
        at com.mongodb.DBCollection.executeBulkWriteOperation(DBCollection.java:2313) ~[mongo-java-driver-3.4.3.jar:?]
        at com.mongodb.DBCollection.executeBulkWriteOperation(DBCollection.java:2302) ~[mongo-java-driver-3.4.3.jar:?]
        at com.mongodb.BulkWriteOperation.execute(BulkWriteOperation.java:121) ~[mongo-java-driver-3.4.3.jar:?]
        at com.ubnt.service.system.null.o00000(Unknown Source) ~[ace.jar:?]
        at com.ubnt.service.devmgr.Ooo0.o00000(Unknown Source) ~[ace.jar:?]
        at com.ubnt.service.devmgr.Ooo0.ö00000(Unknown Source) ~[ace.jar:?]
        at com.ubnt.service.devmgr.Ooo0.superObject(Unknown Source) ~[ace.jar:?]
        at com.ubnt.service.devmgr.Ooo0.o00000(Unknown Source) ~[ace.jar:?]
        at com.ubnt.service.devmgr.KA.o00000(Unknown Source) ~[ace.jar:?]
        at com.ubnt.service.devmgr.oOo0$_o.run(Unknown Source) [ace.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

Possible related to #69 and #83?

**Comment by ryansch** [comment]
I haven't noticed that myself. I'll have to look into it.

**Comment by juriansluiman** [comment]
I will close this one. I have killed the container, started fresh and imported a backup file. Everything went smooth but forgot to report back to here.
